global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "go_app"
    static_configs:
      - targets: ["host.docker.internal:8080"]   # Access Go server

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
